### ISSUE TITLE
Error on execution.

### ISSUE THREAD

**Issue by eduardomarco** [aydinnyunus/WhatsappBOT#15]
PS D:\Users\eduar\Documents\WhatsappBOT>  & 'D:\Users\eduar\AppData\Local\Programs\Python\Python39\python.exe' 'c:\Users\eduar\.vscode\extensions\ms-python.python-2021.9.1191016588\pythonFiles\lib\python\debugpy\launcher' '60895' '--' 'd:\Users\eduar\Documents\WhatsappBOT\WhatsappBot.py' 
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Users\eduar\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "d:\Users\eduar\Documents\WhatsappBOT\WhatsappBot.py", line 346, in Driver
    driver = webdriver.Chrome(executable_path="D:/Users/eduar/Documents/WhatsappBOT/chromedriver", options=options)
  File "D:\Users\eduar\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "D:\Users\eduar\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start    
    self.process = subprocess.Popen(cmd, env=self.env,
  File "D:\Users\eduar\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Users\eduar\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 não é um aplicativo Win32 válido

**Comment by aydinnyunus** [comment]
download compatible chromedriver on https://chromedriver.chromium.org/

**Comment by aydinnyunus** [comment]
then copy to whatsappbot folder and change on the WhatsappBot.py "./chromedriver" to "./chromedriver.exe"
