### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by pretech86** [aydinnyunus/WhatsappBOT#2]
thanks for the tool but when i run python3 WhatsappBot.py i get the following error , i already run pip3 install -r requirments.txt with no error 

Traceback (most recent call last):
  File "WhatsappBot.py", line 35, in <module>
    gif1 = tk.PhotoImage(file='GZd3Pv.png')
  File "/usr/lib/python3.7/tkinter/__init__.py", line 3545, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/lib/python3.7/tkinter/__init__.py", line 3501, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "GZd3Pv.png": no such file or directory

**Comment by aydinnyunus** [comment]
I fixed requirements.txt please install again the libraries with "pip
install -r requirements.txt".
If this does not work.Please say me which options fixed your problem and I
fixed for github repository.

For Linux:

Enter terminal and "pip install python-tk".

For Windows :

https://tkdocs.com/tutorial/install.html

pretech86 <notifications@github.com>, 13 Mar 2020 Cum, 16:08 tarihinde şunu
yazdı:

**Comment by pretech86** [comment]
i already installed requirments and python-tk but also get this 

Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/python-tk/

**Comment by aydinnyunus** [comment]
Try "sudo apt install python3-tk"

**Comment by aydinnyunus** [comment]
I fixed the codes please try again with new codes.Your problem was path of photos.

**Comment by aydinnyunus** [comment]
I fixed the codes please try again with new codes.Your problem was path of photos.

**Comment by pretech86** [comment]
i installed python-tk successfully but when i run python3 WhatsappBot.py  i get this error 

Traceback (most recent call last):
  File "WhatsappBot.py", line 35, in <module>
    gif1 = tk.PhotoImage(file='GZd3Pv.png')
  File "/usr/lib/python3.7/tkinter/__init__.py", line 3545, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/lib/python3.7/tkinter/__init__.py", line 3501, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "GZd3Pv.png": no such file or directory

**Comment by pretech86** [comment]
i install python-tk successfully but when i run python3 WhatsappBot.py i get this error 

Traceback (most recent call last):
  File "WhatsappBot.py", line 40, in <module>
    canvas1.create_image(400, 350, image=gif2)
NameError: name 'gif2' is not defined

**Comment by aydinnyunus** [comment]
Last time try again my bad.

**Comment by pretech86** [comment]
i start already also i changed the path of the chromwebdriver inside the python file but when i try to send message i got this error 

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/opt/WhatsappBOT/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "WhatsappBot.py", line 104, in Driver
    driver = webdriver.Chrome(executable_path="/opt/WhatsappBOT/chromedriver")
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by aydinnyunus** [comment]
Try in terminal "sudo python3 WhatsappBot.py"

**Comment by aydinnyunus** [comment]
This is not code error.

**Comment by pretech86** [comment]
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary

**Comment by aydinnyunus** [comment]
You need to change path of webdriver on python file.

driver = webdriver.Chrome(executable_path="/home/aydinnyunus/Downloads/Birthday-master/chromedriver")
 to

driver = webdriver.Chrome(executable_path="YOUR PATH")

**Comment by aydinnyunus** [comment]
This requirements are at READ.me

**Comment by pretech86** [comment]
i already installed chromedriver and put the path in the script but still get this error 

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "WhatsappBot.py", line 104, in Driver
    driver = webdriver.Chrome(executable_path="/usr/local/lib/node_modules/chromedriver/bin/chromedriver")
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service /usr/local/lib/node_modules/chromedriver/bin/chromedriver unexpectedly exited. Status code was: 1

**Comment by aydinnyunus** [comment]
Solution : https://stackoverflow.com/questions/49323099/webdriverexception-message-service-chromedriver-unexpectedly-exited-status-co

It seems chromedriver needs some extra libraries. This solved the issue for me:

apt-get install -y libglib2.0-0=2.50.3-2 \
libnss3=2:3.26.2-1.1+deb9u1 \
libgconf-2-4=3.2.6-4+b1 \
libfontconfig1=2.11.0-6.7+b1

**Comment by pretech86** [comment]
really thanks for your kindly interest , and i know that i make a big noise for you but i installed all libraries and get the following new error 

Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "WhatsappBot.py", line 104, in Driver
    driver = webdriver.Chrome(executable_path="/usr/local/lib/node_modules/chromedriver/bin/chromedriver")
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service /usr/local/lib/node_modules/chromedriver/bin/chromedriver unexpectedly exited. Status code was: 1

**Comment by pretech86** [comment]
thanks for your kindly interest , and i'm really sorry to interrupt you but i got the following error 

E: Version '2:3.26.2-1.1+deb9u1' for 'libnss3' was not found

**Comment by aydinnyunus** [comment]
Do you have chromium ? Download it : sudo apt-get install -y chromium-browser

**Comment by pretech86** [comment]
sorry for delaying , but i try it many times , i install google chrome and download chromedriver and put its path in the script but , google chrom not start untill i write --n0-sandbox 

and i get the following error 

WhatsappBot.py:108: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path="/root/WhatsappBOT/chromedriver_linux64/chromedriver", options=options)
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "WhatsappBot.py", line 108, in Driver
    driver = webdriver.Chrome(executable_path="/root/WhatsappBOT/chromedriver_linux64/chromedriver", options=options)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 100, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by aydinnyunus** [comment]
I add some new codes.Change user data to your User Data Path.If you don't want to change just delete options part.

**Comment by pretech86** [comment]
i already installed chrome and it run , i get the following error 

hatsappBot.py:108: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path="/usr/local/lib/node_modules/chromedriver", options=options)
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/node_modules/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "WhatsappBot.py", line 108, in Driver
    driver = webdriver.Chrome(executable_path="/usr/local/lib/node_modules/chromedriver", options=options)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 92, in __init__
    self.service.start()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by aydinnyunus** [comment]
try with sudo

**Comment by pretech86** [comment]
i try sudo and try chmod 777 also but oi get the same error ? sorry for interrupting you

**Comment by pretech86** [comment]
root@kali:~/WhatsappBOT1# sudo python3 WhatsappBot.py 
WhatsappBot.py:108: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path="/usr/bin/chromedriver", options=options)
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "WhatsappBot.py", line 108, in Driver
    driver = webdriver.Chrome(executable_path="/usr/bin/chromedriver", options=options)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 92, in __init__
    self.service.start()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service /usr/bin/chromedriver unexpectedly exited. Status code was: 1
