### ISSUE TITLE
ANYONE TO HELP-ME WITH THIS ERROR?

### ISSUE THREAD

**Issue by mendokismo** [aydinnyunus/WhatsappBOT#29]
C:\Users\PC\WhatsappBOT\WhatsappBot.py:354: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path="./chromedriver", options=options)
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\PC\WhatsappBOT\WhatsappBot.py", line 354, in Driver
    driver = webdriver.Chrome(executable_path="./chromedriver", options=options)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 89, in __init__
    self.service.start()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 não é um aplicativo Win32 válido

**Comment by ilias-anouar** [comment]
hey @mendokismo, I have already sent a pull request !! to fix this error I struggled with it too, but it's fixed now I hope the pull request gets merged soon
