### ISSUE TITLE
WhatsappBot

### ISSUE THREAD

**Issue by TechieAV** [aydinnyunus/WhatsappBOT#31]
Here i have an error with code.....
Kindly help to clear the issue

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\VASUNDHARA\Documents\Java\WhatsappBOT-master\WhatsappBot.py", line 110, in Driver
    driver = webdriver.Chrome(executable_path="./chromedriver", options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VASUNDHARA\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\chrome\webdriver.py", line 84, in __init__
    super().__init__(
  File "C:\Users\VASUNDHARA\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\chromium\webdriver.py", line 101, in __init__
    self.service.start()
  File "C:\Users\VASUNDHARA\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\common\service.py", line 96, in start
    self._start_process(self._path)
  File "C:\Users\VASUNDHARA\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\common\service.py", line 197, in _start_process
    self.process = subprocess.Popen(
                   ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1509, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 is not a valid Win32 application
[WhatsappBOT-master.zip](https://github.com/aydinnyunus/WhatsappBOT/files/12558568/WhatsappBOT-master.zip)

**Comment by ilias-anouar** [comment]
hey @TechieAV, already fixed for me, waiting for the pull request to get merged !!!
