### ISSUE TITLE
put executable in the path

### ISSUE THREAD

**Issue by pretech86** [aydinnyunus/WhatsappBOT#5]
i run the tool but and download chromedriver last version and put its path inside the code ( python file ) and install googlechrome but still get the folloiwng error ( my google chrom not starting until i write --no-sandbox )

WhatsappBot.py:108: DeprecationWarning: executable_path has been deprecated, please pass in a Service object

  driver = webdriver.Chrome(executable_path="/root/WhatsappBOT/chromedriver", options=options)

Exception in Tkinter callback

Traceback (most recent call last):

  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__

    return self.func(*args)

  File "WhatsappBot.py", line 108, in Driver

    driver = webdriver.Chrome(executable_path="/root/WhatsappBOT/chromedriver", options=options)

  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 100, in __init__

    desired_capabilities=desired_capabilities)

  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__

    self.start_session(capabilities, browser_profile)

  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session

    response = self.execute(Command.NEW_SESSION, parameters)

  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute

    self.error_handler.check_response(response)

  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response

    raise exception_class(message, screen, stacktrace)

selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.

  (unknown error: DevToolsActivePort file doesn't exist)

  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by aydinnyunus** [comment]
Do you specify the ChromeData part in options=options ? If you want you can delete.

**Comment by pretech86** [comment]
Sorry but can you explain more please ?

**Comment by pretech86** [comment]
i install google chrome and its working fine but still getting this error 

WhatsappBot.py:108: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path="/root/tools/social_engineering/WhatsappBOT/chromedriver", options=options)
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "WhatsappBot.py", line 108, in Driver
    driver = webdriver.Chrome(executable_path="/root/tools/social_engineering/WhatsappBOT/chromedriver", options=options)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 95, in __init__
    RemoteWebDriver.__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /root/tools/social_engineering/WhatsappBOT/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by pretech86** [comment]
i install google chrome and its working fine and when i run the tool it open google chrome without any error but i get this error at the end ( this is new error ) 

WhatsappBot.py:108: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path="/root/tools/social_engineering/WhatsappBOT/chromedriver", options=options)
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "WhatsappBot.py", line 108, in Driver
    driver = webdriver.Chrome(executable_path="/root/tools/social_engineering/WhatsappBOT/chromedriver", options=options)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 95, in __init__
    RemoteWebDriver.__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist

**Comment by pretech86** [comment]
thanks it working

**Comment by aydinnyunus** [comment]
You are welcome
